language: python
python:
    - "2.7"
    - "3.4"
before_install:
    - sudo apt-get install hdf5
install:
    - pip install -r requirements.txt
    - python setup.py install
script:
    - cd test
    - nosetests -vs .
