language: generic

sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++
            - gromacs
            - pypy

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=2.7 NUMPYVER="numpy=1.8" SCIENTIFIC="yes" }
    - { os: linux, env: PYTHON_VERSION=3.3 MINIMAL_PACKAGES=yes NUMPYVER="numpy" }
    - { os: linux, env: PYTHON_VERSION=3.4 NUMPYVER="numpy" }
    - { os: linux, env: PYTHON_VERSION=pypy }
    - { os: osx, env: PYTHON_VERSION=3.4 }

install:
    - source devtools/travis-ci/install.sh
      # install our package
    - python setup.py install

script:
    # Skip tests that use a lot of memory so Travis doesn't sporadically kill
    # them. Also fix the number of running threads to 1.
    - export PARMED_SKIP_BIG_TESTS=1
    - export OPENMM_CPU_THREADS=1
    - echo "Checking parmed source with pyflakes linter"
    - devtools/travis-ci/pyflakes_check.sh
    - cd test
    - echo "Using `which python` (`python -V`)::"
    - nosetests -vs .
